export const SubFilters = {
  NONE: "none",
  TODAY: "today",
  LAST_WEEK: "last week",
  LAST_YEAR: "last year",
  GENERAL: "general",
  SCIENCE: "science",
  SPORTS: "sports",
  BUSINESS: "business",
  HEALTH: "health",
  ENTERTAINMENT: "entertainment",
  TECH: "tech",
  POLITICS: "politics",
  FOOD: "food",
  TRAVEL: "travel",
  POSITIVE: "POSITIVE",
  NEGATIVE: "NEGATIVE",
  NORTHEAST: "northeast",
  MIDWEST: "midwest",
  WEST: "west",
  SOUTH: "south",
};

export const Filters = {
  NONE: "none",
  CATEGORY: "category",
  RECENT: "recent",
  REGION: "region",
  SENTIMENT: "sentiment",
};
